### ISSUE TITLE
External data products for pipeline development

### ISSUE THREAD

**Issue by JenniferKarr** [AstarVienna/METIS_Simulations#25]
There are a variety of external data products that are used by the pipeline. We need to sort out where these come from and  determine whether they will be available for pipeline development, how the pipeline will access the data (e.g. for databases), and if we need to create a mock version for pipeline input. 

List derived from the DRLD
   AO_PSF_MODEL
  ATM_LINE_CAT 
  ATM_PROFILE
  FLUXSTD_CATALOG
  REF_STD_CAT
  IFU_WAVECAL
  LM_LSS_WAVE_GUESS
  N_LSS_WAVE_GUESS
  N_LSS_DIST_SOL
  LM_SYNTH_TRANS
  N_SYNTH_TRANS
  LSF_KERNEL
  LASER_TAB
  PINHOLE_TABLE

**Comment by JenniferKarr** [comment]
Prototype files have been added for the delivery

**Comment by hugobuddel** [comment]
Thanks for adding all these, makes the delivery so much 'nicer'
