### ISSUE TITLE
Automate mjdobs values

### ISSUE THREAD

**Issue by JenniferKarr** [AstarVienna/METIS_Simulations#30]
Currently mjdobs is set explicitly, which, with the variable expansion, can result in multiple files having the same observation date. 

It should be fairly straightforward to automate the mjdobs varlue, so that an input YAML + start time results in a sequence of consecutive observations.

**Comment by JenniferKarr** [comment]
This has been implemented, and described in the README.

**Comment by hugobuddel** [comment]
This is so nice, the automated MJD-OBS values. (Too bad that this means that I cannot hardcode my birthday anymore.)
