### ISSUE TITLE
Resolve issues raised by Lars on Jira

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/METIS_Simulations#31]
Lars raised some issues on Jira that we should resolve:

* https://jira.eso.org/browse/MET-2299
* https://jira.eso.org/browse/MET-2300
* https://jira.eso.org/browse/MET-2301

We can use this as a meta-issue to track those

**Comment by JenniferKarr** [comment]
TPL have been updated to more reasonable (although not yet perfect) values, MJD-OBS is updated.

**Comment by hugobuddel** [comment]
Checking this again, I think we have indeed resolved everything that Lars asked us to change. (Of course in a few days Lars will tell us that we forgot things, but well...)

@astronomyk can you also mark https://jira.eso.org/browse/MET-2299 as resolved?
