### ISSUE TITLE
Create SOF files for the next delivery

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/METIS_Simulations#35]
See https://jira.eso.org/browse/MET-2299 where Lars said

>  here is how I would like the next simulated data delivery to connect a given, simulated file to the DO category it is expected to receive as part of the data reduction chain:
> 
> 1) Create a given, simulated file where the header contains the FITS keys needed to classify it, DPR.{CATG,TYPE,TECH} etc.
> 
> 2) The name of the file and its expected DO-category is listed in a .sof file.
> 
> 3) The basename of the .sof file is the name of a recipe that is supposed to take the FITS file as input.
> 
> 4) Multiple FITS files each with their DO category can be listed in a single .sof file.
> 
> 5) At this stage, there can be several reasons why such a .sof file will not be complete to the point where the recipe would be able to successfully run with it (e.g. missing calibration files). However, the point is to clearly indicate the expected DO category of the simulated FITS file while also providing an example of how that file would be used in the data flow.
> 
> 6) At the final stage, each .sof file will actually be complete with raw and calibration files to provide examples of valid input for each recipe.

**Comment by JenniferKarr** [comment]
Done and merged
