### ISSUE TITLE
Simulation images does not look consistent across different computers

### ISSUE THREAD

**Issue by chyan26** [AstarVienna/METIS_Simulations#43]
I am using Zeus to generated simulation image with ScopeSim release version.  However, I see some dark frames are having 65535 values.  I compared with those images from another computer.  They are not consistent. 

<img width="1010" alt="Screenshot 2024-06-26 at 11 30 47 AM" src="https://github.com/AstarVienna/METIS_Simulations/assets/6767254/3ae0622e-d5ff-4f64-8cec-18be44748bb5">

@gotten will provided the screen shot of the dark frame from another computer.

**Comment by hugobuddel** [comment]
I'm closing this, as it doesn't seem relevant anymore.
