### ISSUE TITLE
Reproducibility of FITS files

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/METIS_Simulations#68]
We have not yet verified that someone else can generate the FITS files and get the same md5sums.

I'm almost there.

Attached are the checksums that I got: [checksums.20241112.edfb8332.large.txt](https://github.com/user-attachments/files/17722636/checksums.20241112.edfb8332.large.txt)

And also a directory listing: [ls.output.20241112.edfb8332.large.txt](https://github.com/user-attachments/files/17722637/ls.output.20241112.edfb8332.large.txt)

These files have different checksums:
- METIS.DARK_2RG_RAW.2024-01-02_00_43_29.fits
- METIS.DARK_GEO_RAW.2024-01-02_00_43_49.fits
- METIS.DARK_IFU_RAW.2024-01-02_00_44_07.fits
- METIS.IFU_OFF_AXIS_PSF_RAW.2024-01-02_00_24_29.fits
- METIS.IFU_RSRF_PINH_RAW.2024-01-02_00_11_39.fits
- METIS.IFU_SCI_RAW.2024-01-02_00_30_35.fits
- METIS.IFU_SKY_RAW.2024-01-02_00_18_08.fits
- METIS.IFU_SKY_RAW.2024-01-02_00_36_36.fits
- METIS.IFU_STD_RAW.2024-01-02_00_12_07.fits
- METIS.LM_IMAGE_SCI_RAW.2024-01-02_00_24_09.fits
- METIS.LM_IMAGE_SKY_RAW.2024-01-02_00_24_12.fits

Interestingly, these all seem to have 'the wrong file size', that is, they are all 32MB, while other files are 8MB.

I'll try to put one of those files somewhere.

Did someone else manage to recreate the FITS files correctly?

**Comment by hugobuddel** [comment]
OK, I see that the larger files are created with NDIT > 1, so they have a BITPIX of -64, while the smaller ones have BITPIX of 8. That is what we would expect yes.

So maybe these larger ones have some floating point errors or so that make them different when I create them. Dunno

**Comment by JenniferKarr** [comment]
I think we saw that last time, before the quanitzation was fixed; the checksums don't work for floating point data. 

I'll re-run set with NDIT=1 for all files, which will do for this release. For future releases we should think about this a bit more, as we'll likely need NDIT > 1 as we move towards more instrumentally accurate data contents.

**Comment by hugobuddel** [comment]
We can also keep the NDIT > 1 right? I think a more realistic simulation is more important than having it perfectly reproducible

**Comment by JenniferKarr** [comment]
That can work too - we keep the download as is, and use the checksums as a test of download integrity rather than reproducibility.

**Comment by JenniferKarr** [comment]
I'll close this as having decided to live with the differences.
