### ISSUE TITLE
We should either include a PERSISTENCE_MAP.fits or remove the PERSISTENCE_MAP from the SOF files

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/METIS_Simulations#70]
Currently the SOF files mention the PERSISTENCE_MAP, but we are not planning to create a persistence map recipe for this delivery. 

This means that most SOF files cannot actually run.

So we should either add a single PERSISTENCE_MAP fits file, or we should just remove it from the SOF files. I propose removing the PERSISTENCE_MAP form the SOF files, because having it their also risks opening a whole can of worms that we planned to ignore for now.

By the way, before making any changes to the SOF files, please merge https://github.com/AstarVienna/METIS_Simulations/pull/69 first, because otherwise there will probably be conflicts.

**Comment by JenniferKarr** [comment]
Removing for now is okay with me.

**Comment by JenniferKarr** [comment]
Pull request created.

**Comment by hugobuddel** [comment]
Thanks!

Just noting this to link things together: https://github.com/AstarVienna/METIS_Simulations/pull/73

I suppose you'd also need to remove the persistence from the sofTemplates then right? But I'll leave that up to you.

There now is a (fake) PERSISTENCE_MAP.fits in https://github.com/AstarVienna/METIS_Pipeline_Test_Data/tree/main/metis_sim_small_1 but I think that is fine for now because that is just for us internally.
